# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

defaults: &defaults
  working_directory: ~/vts
  docker:
    - image: circleci/node:10.15.3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: 
          name: Run Tests
          command: npm run test

      # create dist
      - run: 
          name: Run Build
          command: npm run build

      # save dist
      - persist_to_workspace:
          root: ~/vts
          paths: .


  coverage:
    <<: *defaults

    steps:
      # reuse build workspace
      - attach_to_workspace:
          at: ~/vts

      # run coverage
      # needs:
      # COVERALLS_SERVICE_NAME=circleci
      # COVERALLS_REPO_TOKEN=token in coveralls.io
      - run:
          name: Collect Coverage
          command: npm run coverage


  publish:
    <<: *defaults

    steps:
      # reuse build workspace
      - attach_to_workspace:
          at: ~/vts

      # save NPM_TOKEN in npmrc config file
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run: 
          name: Publish NPM Package
          command: npm publish --access public


workflows:
  version: 2
  main:
    jobs:
      - build

      - coverage:
          requires:
            - build
          filters:
            branches:
              only: master

      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
